{% set name = "eza" %}
{% set version = "0.21.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eza-community/eza/archive/v{{ version }}.tar.gz
  sha256: f0827d39406f0799e6676ab87e349193e88b6220af1670e98b988e8ee0c2b7c0

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - eza --help
    - eza --icons --long --git --header

about:
  home: https://eza.rocks/
  summary: A modern, maintained replacement for ls.
  license: EUPL-1.2
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml

  description: |
    eza is a modern, maintained replacement for the venerable 
    file-listing command-line program ls that ships with Unix 
    and Linux operating systems, giving it more features and 
    better defaults. It uses colours to distinguish file types 
    and metadata. It knows about symlinks, extended attributes, and Git. 
    And it’s small, fast, and just one single binary.
  dev_url: https://github.com/eza-community/eza

extra:
  recipe-maintainers:
    - synapticarbors
    - dbast
