{% set name = "eza" %}
{% set version = "0.20.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eza-community/eza/archive/v{{ version }}.tar.gz
  sha256: be5eb8d314f817bbfdcad4d21e66d2a8c4006ba4619735297b5233887ebdbe99

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses

test:
  commands:
    - eza --help
    - eza --icons --long --git --header

about:
  home: https://eza.rocks/
  summary: A modern, maintained replacement for ls.
  license: EUPL-1.2
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml

  description: |
    eza is a modern, maintained replacement for the venerable 
    file-listing command-line program ls that ships with Unix 
    and Linux operating systems, giving it more features and 
    better defaults. It uses colours to distinguish file types 
    and metadata. It knows about symlinks, extended attributes, and Git. 
    And it’s small, fast, and just one single binary.
  dev_url: https://github.com/eza-community/eza

extra:
  recipe-maintainers:
    - synapticarbors
    - dbast
