{% set name = "eza" %}
{% set version = "0.18.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eza-community/eza/archive/v{{ version }}.tar.gz
  sha256: 92d810c36ac67038e2ed3c421087de8793eb0b9de332c9239096df9d52eb30e3

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  run:

test:
  commands:
    - eza --help

about:
  home: https://github.com/eza-community/eza
  summary: A modern, maintained replacement for ls.
  license: MIT
  license_family: MIT
  license_file:
    - LICENCE
    - THIRDPARTY.yml

  description: |
    eza is a modern, maintained replacement for the venerable 
    file-listing command-line program ls that ships with Unix 
    and Linux operating systems, giving it more features and 
    better defaults. It uses colours to distinguish file types 
    and metadata. It knows about symlinks, extended attributes, and Git. 
    And it’s small, fast, and just one single binary.
  dev_url: https://github.com/eza-community/eza

extra:
  recipe-maintainers:
    - synapticarbors
