{% set name = "eza" %}
{% set version = "0.18.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/eza-community/eza/archive/v{{ version }}.tar.gz
  sha256: 679fd3b5b389553aa77a2bce496e8658848ef0f4624968fd1a330dbe92032438

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  run:

test:
  commands:
    - eza --help

about:
  home: https://github.com/eza-community/eza
  summary: A modern, maintained replacement for ls.
  license: MIT
  license_family: MIT
  license_file:
    - LICENCE
    - THIRDPARTY.yml

  description: |
    eza is a modern, maintained replacement for the venerable 
    file-listing command-line program ls that ships with Unix 
    and Linux operating systems, giving it more features and 
    better defaults. It uses colours to distinguish file types 
    and metadata. It knows about symlinks, extended attributes, and Git. 
    And it’s small, fast, and just one single binary.
  dev_url: https://github.com/eza-community/eza

extra:
  recipe-maintainers:
    - synapticarbors
