schema_version: 1

context:
  name: eza
  version: "0.23.1"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://github.com/eza-community/eza/archive/v${{ version }}.tar.gz
  sha256: 4c49f3ee6fc76ef45c489cd664eb2c68d96cda31b427605a48b074bcf269ee05

build:
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib("c") }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses

tests:
  - script:
      - eza --help
      - eza --icons --long --git --header

about:
  summary: A modern, maintained replacement for ls.
  license: EUPL-1.2
  license_file:
    - LICENSE.txt
    - THIRDPARTY.yml
  description: |
    eza is a modern, maintained replacement for the venerable
    file-listing command-line program ls that ships with Unix
    and Linux operating systems, giving it more features and
    better defaults. It uses colours to distinguish file types
    and metadata. It knows about symlinks, extended attributes, and Git.
    And it’s small, fast, and just one single binary.
  homepage: https://eza.rocks/
  repository: https://github.com/eza-community/eza

extra:
  recipe-maintainers:
    - synapticarbors
    - dbast
